version: '3.8'

services:
  node-app:
    build: .
    image: node-app
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      - postgresdb
    volumes:
      - .:/usr/src/node-app
      - ./prisma:/usr/src/app/prisma
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3000}
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:password@postgresdb:5432/problem5?schema=public}
    networks:
      - node-network

  postgresdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-problem5}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - node-network

networks:
  node-network:
    driver: bridge

volumes:
  dbdata:
